# Generated by Django 2.2.4 on 2020-07-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='1981-01-11'),
            preserve_default=False,
        ),
    ]
